import json
import os
import urllib.error
import urllib.request

GOOGLE_API_BASE = "https://generativelanguage.googleapis.com/v1beta/models"
# Overridable via GOOGLE_MODEL so a team can point this at whatever Gemini
# model their API key has access to without touching code.
GOOGLE_MODEL = os.environ.get("GOOGLE_MODEL", "gemini-2.5-flash")


def _flatten_messages(messages):
    """MCP sampling `messages` -> Gemini `contents` (role "assistant" ->
    "model", per the Gemini API's role naming)."""
    contents = []
    for m in messages:
        content = m.get("content", {})
        text = content.get("text", "") if isinstance(content, dict) else str(content)
        role = "model" if m.get("role") == "assistant" else "user"
        contents.append({"role": role, "parts": [{"text": text}]})
    return contents


def _call_google(messages, system_prompt, max_tokens):
    api_key = os.environ.get("GOOGLE_API_KEY") or os.environ.get("GEMINI_API_KEY")
    if not api_key:
        return None

    body = {
        "contents": _flatten_messages(messages),
        "generationConfig": {"maxOutputTokens": max_tokens},
    }
    if system_prompt:
        body["systemInstruction"] = {"parts": [{"text": system_prompt}]}

    url = f"{GOOGLE_API_BASE}/{GOOGLE_MODEL}:generateContent?key={api_key}"
    req = urllib.request.Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers={"content-type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        candidates = data.get("candidates", [])
        if not candidates:
            return None
        parts = candidates[0].get("content", {}).get("parts", [])
        text = "".join(p.get("text", "") for p in parts).strip()
        return text or None
    except (urllib.error.URLError, urllib.error.HTTPError, KeyError, ValueError, TimeoutError):
        return None


def _fallback_risk_assessment(messages):
    """Deterministic stand-in when no ANTHROPIC_API_KEY is configured.
    Reads the container facts the server embedded in the message text and
    applies the same rules hazmat_policy.md / customs_policy.md describe,
    so the tool call still resolves to a real, checkable answer offline."""
    joined = "\n".join((m.get("content", {}) or {}).get("text", "") for m in messages).lower()

    hazmat = any(s in joined for s in ("hazmat: yes", "hazmat=true", "hazmat is true", '"hazmat": true', "hazardous material: yes"))
    on_hold = "hold" in joined and "active" in joined
    suspended = "suspended" in joined

    if hazmat and on_hold:
        level = "High"
        factors = "Hazardous material flag AND an active customs hold on this container."
        approvals = "Customs officer must clear the hold; supervisor must approve the release."
    elif suspended:
        level = "High"
        factors = "Carrier/trucking company is suspended."
        approvals = "Container cannot be released to this carrier under any circumstances."
    elif hazmat:
        level = "Medium"
        factors = "Hazardous material flag, no active customs hold."
        approvals = "Supervisor approval required before release."
    elif on_hold:
        level = "Medium"
        factors = "Active customs hold, no hazmat flag."
        approvals = "Customs officer must clear the hold before release."
    else:
        level = "Low"
        factors = "No hazmat flag, no active hold, carrier active."
        approvals = "None beyond standard dispatcher sign-off."

    recommendation = (
        "Escalate to supervisor/customs before any release action."
        if level != "Low"
        else "Safe to proceed with the standard release process."
    )

    return (
        f"Risk Level:\n{level}\n\n"
        f"Risk Factors:\n{factors}\n\n"
        f"Required Approvals:\n{approvals}\n\n"
        f"Recommendation:\n{recommendation}\n\n"
        f"[fallback: no GOOGLE_API_KEY/GEMINI_API_KEY configured — generated by a "
        f"local rule engine, not a live model call]"
    )


def sampling_handler(messages, system_prompt, max_tokens):
    """Registered on MCPClient as the sampling/createMessage responder."""
    print("\n" + "=" * 70)
    print("SAMPLING REQUEST (sampling/createMessage) — reasoning on the CLIENT")
    print("-" * 70)

    text = _call_google(messages, system_prompt, max_tokens)
    used_live_model = text is not None
    if text is None:
        text = _fallback_risk_assessment(messages)

    print(f"[{'live Google Gemini API call' if used_live_model else 'offline fallback rule engine'}]")
    print(text)
    print("=" * 70)

    return {"role": "assistant", "content": {"type": "text", "text": text}}
